//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionEnabledRepo) DeepCopyInto(out *ActionEnabledRepo) {
	*out = *in
	if in.RepoRef != nil {
		in, out := &in.RepoRef, &out.RepoRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoSelector != nil {
		in, out := &in.RepoSelector, &out.RepoSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionEnabledRepo.
func (in *ActionEnabledRepo) DeepCopy() *ActionEnabledRepo {
	if in == nil {
		return nil
	}
	out := new(ActionEnabledRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsConfiguration) DeepCopyInto(out *ActionsConfiguration) {
	*out = *in
	if in.EnabledRepos != nil {
		in, out := &in.EnabledRepos, &out.EnabledRepos
		*out = make([]ActionEnabledRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsConfiguration.
func (in *ActionsConfiguration) DeepCopy() *ActionsConfiguration {
	if in == nil {
		return nil
	}
	out := new(ActionsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccess) DeepCopyInto(out *ActionsSecretAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccess.
func (in *ActionsSecretAccess) DeepCopy() *ActionsSecretAccess {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionsSecretAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccessList) DeepCopyInto(out *ActionsSecretAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActionsSecretAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccessList.
func (in *ActionsSecretAccessList) DeepCopy() *ActionsSecretAccessList {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionsSecretAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccessObservation) DeepCopyInto(out *ActionsSecretAccessObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccessObservation.
func (in *ActionsSecretAccessObservation) DeepCopy() *ActionsSecretAccessObservation {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccessParameters) DeepCopyInto(out *ActionsSecretAccessParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedRepositories != nil {
		in, out := &in.SelectedRepositories, &out.SelectedRepositories
		*out = make([]SecretSelectedRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccessParameters.
func (in *ActionsSecretAccessParameters) DeepCopy() *ActionsSecretAccessParameters {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccessSpec) DeepCopyInto(out *ActionsSecretAccessSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccessSpec.
func (in *ActionsSecretAccessSpec) DeepCopy() *ActionsSecretAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSecretAccessStatus) DeepCopyInto(out *ActionsSecretAccessStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSecretAccessStatus.
func (in *ActionsSecretAccessStatus) DeepCopy() *ActionsSecretAccessStatus {
	if in == nil {
		return nil
	}
	out := new(ActionsSecretAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionRestrictions) DeepCopyInto(out *BranchProtectionRestrictions) {
	*out = *in
	if in.BlockCreations != nil {
		in, out := &in.BlockCreations, &out.BlockCreations
		*out = new(bool)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionRestrictions.
func (in *BranchProtectionRestrictions) DeepCopy() *BranchProtectionRestrictions {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionRestrictions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionRule) DeepCopyInto(out *BranchProtectionRule) {
	*out = *in
	if in.RequiredStatusChecks != nil {
		in, out := &in.RequiredStatusChecks, &out.RequiredStatusChecks
		*out = new(RequiredStatusChecks)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredPullRequestReviews != nil {
		in, out := &in.RequiredPullRequestReviews, &out.RequiredPullRequestReviews
		*out = new(RequiredPullRequestReviews)
		(*in).DeepCopyInto(*out)
	}
	if in.BranchProtectionRestrictions != nil {
		in, out := &in.BranchProtectionRestrictions, &out.BranchProtectionRestrictions
		*out = new(BranchProtectionRestrictions)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireLinearHistory != nil {
		in, out := &in.RequireLinearHistory, &out.RequireLinearHistory
		*out = new(bool)
		**out = **in
	}
	if in.AllowForcePushes != nil {
		in, out := &in.AllowForcePushes, &out.AllowForcePushes
		*out = new(bool)
		**out = **in
	}
	if in.AllowDeletions != nil {
		in, out := &in.AllowDeletions, &out.AllowDeletions
		*out = new(bool)
		**out = **in
	}
	if in.RequiredConversationResolution != nil {
		in, out := &in.RequiredConversationResolution, &out.RequiredConversationResolution
		*out = new(bool)
		**out = **in
	}
	if in.LockBranch != nil {
		in, out := &in.LockBranch, &out.LockBranch
		*out = new(bool)
		**out = **in
	}
	if in.AllowForkSyncing != nil {
		in, out := &in.AllowForkSyncing, &out.AllowForkSyncing
		*out = new(bool)
		**out = **in
	}
	if in.RequireSignedCommits != nil {
		in, out := &in.RequireSignedCommits, &out.RequireSignedCommits
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionRule.
func (in *BranchProtectionRule) DeepCopy() *BranchProtectionRule {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BypassPullRequestAllowancesRequest) DeepCopyInto(out *BypassPullRequestAllowancesRequest) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BypassPullRequestAllowancesRequest.
func (in *BypassPullRequestAllowancesRequest) DeepCopy() *BypassPullRequestAllowancesRequest {
	if in == nil {
		return nil
	}
	out := new(BypassPullRequestAllowancesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccess) DeepCopyInto(out *DependabotSecretAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccess.
func (in *DependabotSecretAccess) DeepCopy() *DependabotSecretAccess {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependabotSecretAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccessList) DeepCopyInto(out *DependabotSecretAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DependabotSecretAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccessList.
func (in *DependabotSecretAccessList) DeepCopy() *DependabotSecretAccessList {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependabotSecretAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccessObservation) DeepCopyInto(out *DependabotSecretAccessObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccessObservation.
func (in *DependabotSecretAccessObservation) DeepCopy() *DependabotSecretAccessObservation {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccessParameters) DeepCopyInto(out *DependabotSecretAccessParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedRepositories != nil {
		in, out := &in.SelectedRepositories, &out.SelectedRepositories
		*out = make([]SecretSelectedRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccessParameters.
func (in *DependabotSecretAccessParameters) DeepCopy() *DependabotSecretAccessParameters {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccessSpec) DeepCopyInto(out *DependabotSecretAccessSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccessSpec.
func (in *DependabotSecretAccessSpec) DeepCopy() *DependabotSecretAccessSpec {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependabotSecretAccessStatus) DeepCopyInto(out *DependabotSecretAccessStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependabotSecretAccessStatus.
func (in *DependabotSecretAccessStatus) DeepCopy() *DependabotSecretAccessStatus {
	if in == nil {
		return nil
	}
	out := new(DependabotSecretAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DismissalRestrictionsRequest) DeepCopyInto(out *DismissalRestrictionsRequest) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DismissalRestrictionsRequest.
func (in *DismissalRestrictionsRequest) DeepCopy() *DismissalRestrictionsRequest {
	if in == nil {
		return nil
	}
	out := new(DismissalRestrictionsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Membership) DeepCopyInto(out *Membership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Membership.
func (in *Membership) DeepCopy() *Membership {
	if in == nil {
		return nil
	}
	out := new(Membership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Membership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembershipList) DeepCopyInto(out *MembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Membership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembershipList.
func (in *MembershipList) DeepCopy() *MembershipList {
	if in == nil {
		return nil
	}
	out := new(MembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembershipObservation) DeepCopyInto(out *MembershipObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembershipObservation.
func (in *MembershipObservation) DeepCopy() *MembershipObservation {
	if in == nil {
		return nil
	}
	out := new(MembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembershipParameters) DeepCopyInto(out *MembershipParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembershipParameters.
func (in *MembershipParameters) DeepCopy() *MembershipParameters {
	if in == nil {
		return nil
	}
	out := new(MembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembershipSpec) DeepCopyInto(out *MembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembershipSpec.
func (in *MembershipSpec) DeepCopy() *MembershipSpec {
	if in == nil {
		return nil
	}
	out := new(MembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembershipStatus) DeepCopyInto(out *MembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembershipStatus.
func (in *MembershipStatus) DeepCopy() *MembershipStatus {
	if in == nil {
		return nil
	}
	out := new(MembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgSecret) DeepCopyInto(out *OrgSecret) {
	*out = *in
	if in.RepositoryAccessList != nil {
		in, out := &in.RepositoryAccessList, &out.RepositoryAccessList
		*out = make([]SecretSelectedRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgSecret.
func (in *OrgSecret) DeepCopy() *OrgSecret {
	if in == nil {
		return nil
	}
	out := new(OrgSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationObservation) DeepCopyInto(out *OrganizationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationObservation.
func (in *OrganizationObservation) DeepCopy() *OrganizationObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationParameters) DeepCopyInto(out *OrganizationParameters) {
	*out = *in
	in.Actions.DeepCopyInto(&out.Actions)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(SecretConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationParameters.
func (in *OrganizationParameters) DeepCopy() *OrganizationParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariable) DeepCopyInto(out *OrganizationVariable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariable.
func (in *OrganizationVariable) DeepCopy() *OrganizationVariable {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationVariable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariableList) DeepCopyInto(out *OrganizationVariableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrganizationVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariableList.
func (in *OrganizationVariableList) DeepCopy() *OrganizationVariableList {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationVariableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariableObservation) DeepCopyInto(out *OrganizationVariableObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariableObservation.
func (in *OrganizationVariableObservation) DeepCopy() *OrganizationVariableObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariableParameters) DeepCopyInto(out *OrganizationVariableParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedRepositories != nil {
		in, out := &in.SelectedRepositories, &out.SelectedRepositories
		*out = make([]VariableSelectedRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariableParameters.
func (in *OrganizationVariableParameters) DeepCopy() *OrganizationVariableParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariableSpec) DeepCopyInto(out *OrganizationVariableSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariableSpec.
func (in *OrganizationVariableSpec) DeepCopy() *OrganizationVariableSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationVariableStatus) DeepCopyInto(out *OrganizationVariableStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationVariableStatus.
func (in *OrganizationVariableStatus) DeepCopy() *OrganizationVariableStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationVariableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhook) DeepCopyInto(out *OrganizationWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhook.
func (in *OrganizationWebhook) DeepCopy() *OrganizationWebhook {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhookList) DeepCopyInto(out *OrganizationWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrganizationWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhookList.
func (in *OrganizationWebhookList) DeepCopy() *OrganizationWebhookList {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhookObservation) DeepCopyInto(out *OrganizationWebhookObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhookObservation.
func (in *OrganizationWebhookObservation) DeepCopy() *OrganizationWebhookObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhookObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhookParameters) DeepCopyInto(out *OrganizationWebhookParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.InsecureSsl != nil {
		in, out := &in.InsecureSsl, &out.InsecureSsl
		*out = new(bool)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhookParameters.
func (in *OrganizationWebhookParameters) DeepCopy() *OrganizationWebhookParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhookParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhookSpec) DeepCopyInto(out *OrganizationWebhookSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhookSpec.
func (in *OrganizationWebhookSpec) DeepCopy() *OrganizationWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationWebhookStatus) DeepCopyInto(out *OrganizationWebhookStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationWebhookStatus.
func (in *OrganizationWebhookStatus) DeepCopy() *OrganizationWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationWebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoFork) DeepCopyInto(out *RepoFork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoFork.
func (in *RepoFork) DeepCopy() *RepoFork {
	if in == nil {
		return nil
	}
	out := new(RepoFork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryObservation) DeepCopyInto(out *RepositoryObservation) {
	*out = *in
	if in.UnappliedBranchProtection != nil {
		in, out := &in.UnappliedBranchProtection, &out.UnappliedBranchProtection
		*out = make([]UnappliedBranchProtection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnappliedSettings != nil {
		in, out := &in.UnappliedSettings, &out.UnappliedSettings
		*out = make([]UnappliedSetting, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryObservation.
func (in *RepositoryObservation) DeepCopy() *RepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryParameters) DeepCopyInto(out *RepositoryParameters) {
	*out = *in
	in.Permissions.DeepCopyInto(&out.Permissions)
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = make([]RepositoryWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BranchProtectionRules != nil {
		in, out := &in.BranchProtectionRules, &out.BranchProtectionRules
		*out = make([]BranchProtectionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RepositoryRules != nil {
		in, out := &in.RepositoryRules, &out.RepositoryRules
		*out = new([]RepositoryRuleset)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RepositoryRuleset, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.CreateFromTemplate != nil {
		in, out := &in.CreateFromTemplate, &out.CreateFromTemplate
		*out = new(TemplateRepo)
		**out = **in
	}
	if in.CreateFork != nil {
		in, out := &in.CreateFork, &out.CreateFork
		*out = new(RepoFork)
		**out = **in
	}
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.ForceDelete != nil {
		in, out := &in.ForceDelete, &out.ForceDelete
		*out = new(bool)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.IsTemplate != nil {
		in, out := &in.IsTemplate, &out.IsTemplate
		*out = new(bool)
		**out = **in
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.AllowMergeCommit != nil {
		in, out := &in.AllowMergeCommit, &out.AllowMergeCommit
		*out = new(bool)
		**out = **in
	}
	if in.AllowSquashMerge != nil {
		in, out := &in.AllowSquashMerge, &out.AllowSquashMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseMerge != nil {
		in, out := &in.AllowRebaseMerge, &out.AllowRebaseMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowAutoMerge != nil {
		in, out := &in.AllowAutoMerge, &out.AllowAutoMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowUpdateBranch != nil {
		in, out := &in.AllowUpdateBranch, &out.AllowUpdateBranch
		*out = new(bool)
		**out = **in
	}
	if in.DeleteBranchOnMerge != nil {
		in, out := &in.DeleteBranchOnMerge, &out.DeleteBranchOnMerge
		*out = new(bool)
		**out = **in
	}
	if in.HasIssues != nil {
		in, out := &in.HasIssues, &out.HasIssues
		*out = new(bool)
		**out = **in
	}
	if in.HasProjects != nil {
		in, out := &in.HasProjects, &out.HasProjects
		*out = new(bool)
		**out = **in
	}
	if in.HasWiki != nil {
		in, out := &in.HasWiki, &out.HasWiki
		*out = new(bool)
		**out = **in
	}
	if in.HasDiscussions != nil {
		in, out := &in.HasDiscussions, &out.HasDiscussions
		*out = new(bool)
		**out = **in
	}
	if in.MergeCommitTitle != nil {
		in, out := &in.MergeCommitTitle, &out.MergeCommitTitle
		*out = new(string)
		**out = **in
	}
	if in.MergeCommitMessage != nil {
		in, out := &in.MergeCommitMessage, &out.MergeCommitMessage
		*out = new(string)
		**out = **in
	}
	if in.SquashMergeCommitTitle != nil {
		in, out := &in.SquashMergeCommitTitle, &out.SquashMergeCommitTitle
		*out = new(string)
		**out = **in
	}
	if in.SquashMergeCommitMessage != nil {
		in, out := &in.SquashMergeCommitMessage, &out.SquashMergeCommitMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryParameters.
func (in *RepositoryParameters) DeepCopy() *RepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryPermissions) DeepCopyInto(out *RepositoryPermissions) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]RepositoryUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]RepositoryTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryPermissions.
func (in *RepositoryPermissions) DeepCopy() *RepositoryPermissions {
	if in == nil {
		return nil
	}
	out := new(RepositoryPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryRuleset) DeepCopyInto(out *RepositoryRuleset) {
	*out = *in
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
	if in.BypassActors != nil {
		in, out := &in.BypassActors, &out.BypassActors
		*out = make([]*RulesetByPassActors, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RulesetByPassActors)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(RulesetConditions)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(Rules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryRuleset.
func (in *RepositoryRuleset) DeepCopy() *RepositoryRuleset {
	if in == nil {
		return nil
	}
	out := new(RepositoryRuleset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryTeam) DeepCopyInto(out *RepositoryTeam) {
	*out = *in
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.TeamSelector != nil {
		in, out := &in.TeamSelector, &out.TeamSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryTeam.
func (in *RepositoryTeam) DeepCopy() *RepositoryTeam {
	if in == nil {
		return nil
	}
	out := new(RepositoryTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryUser) DeepCopyInto(out *RepositoryUser) {
	*out = *in
	if in.UserRef != nil {
		in, out := &in.UserRef, &out.UserRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserSelector != nil {
		in, out := &in.UserSelector, &out.UserSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryUser.
func (in *RepositoryUser) DeepCopy() *RepositoryUser {
	if in == nil {
		return nil
	}
	out := new(RepositoryUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhook) DeepCopyInto(out *RepositoryWebhook) {
	*out = *in
	if in.InsecureSsl != nil {
		in, out := &in.InsecureSsl, &out.InsecureSsl
		*out = new(bool)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhook.
func (in *RepositoryWebhook) DeepCopy() *RepositoryWebhook {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredPullRequestReviews) DeepCopyInto(out *RequiredPullRequestReviews) {
	*out = *in
	if in.RequireLastPushApproval != nil {
		in, out := &in.RequireLastPushApproval, &out.RequireLastPushApproval
		*out = new(bool)
		**out = **in
	}
	if in.BypassPullRequestAllowances != nil {
		in, out := &in.BypassPullRequestAllowances, &out.BypassPullRequestAllowances
		*out = new(BypassPullRequestAllowancesRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.DismissalRestrictions != nil {
		in, out := &in.DismissalRestrictions, &out.DismissalRestrictions
		*out = new(DismissalRestrictionsRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredPullRequestReviews.
func (in *RequiredPullRequestReviews) DeepCopy() *RequiredPullRequestReviews {
	if in == nil {
		return nil
	}
	out := new(RequiredPullRequestReviews)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredStatusCheck) DeepCopyInto(out *RequiredStatusCheck) {
	*out = *in
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredStatusCheck.
func (in *RequiredStatusCheck) DeepCopy() *RequiredStatusCheck {
	if in == nil {
		return nil
	}
	out := new(RequiredStatusCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredStatusChecks) DeepCopyInto(out *RequiredStatusChecks) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]*RequiredStatusCheck, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RequiredStatusCheck)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredStatusChecks.
func (in *RequiredStatusChecks) DeepCopy() *RequiredStatusChecks {
	if in == nil {
		return nil
	}
	out := new(RequiredStatusChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rules) DeepCopyInto(out *Rules) {
	*out = *in
	if in.Creation != nil {
		in, out := &in.Creation, &out.Creation
		*out = new(bool)
		**out = **in
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(bool)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(bool)
		**out = **in
	}
	if in.UpdateAllowsFetchAndMerge != nil {
		in, out := &in.UpdateAllowsFetchAndMerge, &out.UpdateAllowsFetchAndMerge
		*out = new(bool)
		**out = **in
	}
	if in.RequiredLinearHistory != nil {
		in, out := &in.RequiredLinearHistory, &out.RequiredLinearHistory
		*out = new(bool)
		**out = **in
	}
	if in.RequiredDeployments != nil {
		in, out := &in.RequiredDeployments, &out.RequiredDeployments
		*out = new(RulesRequiredDeployments)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredSignatures != nil {
		in, out := &in.RequiredSignatures, &out.RequiredSignatures
		*out = new(bool)
		**out = **in
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(RulesPullRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredStatusChecks != nil {
		in, out := &in.RequiredStatusChecks, &out.RequiredStatusChecks
		*out = new(RulesRequiredStatusChecks)
		(*in).DeepCopyInto(*out)
	}
	if in.NonFastForward != nil {
		in, out := &in.NonFastForward, &out.NonFastForward
		*out = new(bool)
		**out = **in
	}
	if in.MergeQueue != nil {
		in, out := &in.MergeQueue, &out.MergeQueue
		*out = new(RulesMergeQueue)
		**out = **in
	}
	if in.CommitMessagePattern != nil {
		in, out := &in.CommitMessagePattern, &out.CommitMessagePattern
		*out = new(RulesPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitAuthorEmailPattern != nil {
		in, out := &in.CommitAuthorEmailPattern, &out.CommitAuthorEmailPattern
		*out = new(RulesPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitterEmailPattern != nil {
		in, out := &in.CommitterEmailPattern, &out.CommitterEmailPattern
		*out = new(RulesPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.BranchNamePattern != nil {
		in, out := &in.BranchNamePattern, &out.BranchNamePattern
		*out = new(RulesPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.TagNamePattern != nil {
		in, out := &in.TagNamePattern, &out.TagNamePattern
		*out = new(RulesPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeScanning != nil {
		in, out := &in.CodeScanning, &out.CodeScanning
		*out = new(RulesCodeScanning)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeQuality != nil {
		in, out := &in.CodeQuality, &out.CodeQuality
		*out = new(RulesCodeQuality)
		**out = **in
	}
	if in.CodeCoverage != nil {
		in, out := &in.CodeCoverage, &out.CodeCoverage
		*out = new(RulesCodeCoverage)
		(*in).DeepCopyInto(*out)
	}
	if in.LicenseComplianceScanning != nil {
		in, out := &in.LicenseComplianceScanning, &out.LicenseComplianceScanning
		*out = new(bool)
		**out = **in
	}
	if in.RequireSecretScanningAlertResolution != nil {
		in, out := &in.RequireSecretScanningAlertResolution, &out.RequireSecretScanningAlertResolution
		*out = new(RulesSecretScanningAlertResolution)
		(*in).DeepCopyInto(*out)
	}
	if in.CopilotCodeReview != nil {
		in, out := &in.CopilotCodeReview, &out.CopilotCodeReview
		*out = new(RulesCopilotCodeReview)
		(*in).DeepCopyInto(*out)
	}
	if in.FileExtensionRestriction != nil {
		in, out := &in.FileExtensionRestriction, &out.FileExtensionRestriction
		*out = new(RulesFileExtensionRestriction)
		(*in).DeepCopyInto(*out)
	}
	if in.FilePathRestriction != nil {
		in, out := &in.FilePathRestriction, &out.FilePathRestriction
		*out = new(RulesFilePathRestriction)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxFilePathLength != nil {
		in, out := &in.MaxFilePathLength, &out.MaxFilePathLength
		*out = new(RulesMaxFilePathLength)
		**out = **in
	}
	if in.MaxFileSize != nil {
		in, out := &in.MaxFileSize, &out.MaxFileSize
		*out = new(RulesMaxFileSize)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rules.
func (in *Rules) DeepCopy() *Rules {
	if in == nil {
		return nil
	}
	out := new(Rules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesCodeCoverage) DeepCopyInto(out *RulesCodeCoverage) {
	*out = *in
	if in.MinimumCoverage != nil {
		in, out := &in.MinimumCoverage, &out.MinimumCoverage
		*out = new(string)
		**out = **in
	}
	if in.MaxCoverageDrop != nil {
		in, out := &in.MaxCoverageDrop, &out.MaxCoverageDrop
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesCodeCoverage.
func (in *RulesCodeCoverage) DeepCopy() *RulesCodeCoverage {
	if in == nil {
		return nil
	}
	out := new(RulesCodeCoverage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesCodeQuality) DeepCopyInto(out *RulesCodeQuality) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesCodeQuality.
func (in *RulesCodeQuality) DeepCopy() *RulesCodeQuality {
	if in == nil {
		return nil
	}
	out := new(RulesCodeQuality)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesCodeScanning) DeepCopyInto(out *RulesCodeScanning) {
	*out = *in
	if in.CodeScanningTools != nil {
		in, out := &in.CodeScanningTools, &out.CodeScanningTools
		*out = make([]*RulesCodeScanningTool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RulesCodeScanningTool)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesCodeScanning.
func (in *RulesCodeScanning) DeepCopy() *RulesCodeScanning {
	if in == nil {
		return nil
	}
	out := new(RulesCodeScanning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesCodeScanningTool) DeepCopyInto(out *RulesCodeScanningTool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesCodeScanningTool.
func (in *RulesCodeScanningTool) DeepCopy() *RulesCodeScanningTool {
	if in == nil {
		return nil
	}
	out := new(RulesCodeScanningTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesCopilotCodeReview) DeepCopyInto(out *RulesCopilotCodeReview) {
	*out = *in
	if in.ReviewOnPush != nil {
		in, out := &in.ReviewOnPush, &out.ReviewOnPush
		*out = new(bool)
		**out = **in
	}
	if in.ReviewDraftPullRequests != nil {
		in, out := &in.ReviewDraftPullRequests, &out.ReviewDraftPullRequests
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesCopilotCodeReview.
func (in *RulesCopilotCodeReview) DeepCopy() *RulesCopilotCodeReview {
	if in == nil {
		return nil
	}
	out := new(RulesCopilotCodeReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesDismissalActor) DeepCopyInto(out *RulesDismissalActor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesDismissalActor.
func (in *RulesDismissalActor) DeepCopy() *RulesDismissalActor {
	if in == nil {
		return nil
	}
	out := new(RulesDismissalActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesDismissalRestriction) DeepCopyInto(out *RulesDismissalRestriction) {
	*out = *in
	if in.AllowedActors != nil {
		in, out := &in.AllowedActors, &out.AllowedActors
		*out = make([]*RulesDismissalActor, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RulesDismissalActor)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesDismissalRestriction.
func (in *RulesDismissalRestriction) DeepCopy() *RulesDismissalRestriction {
	if in == nil {
		return nil
	}
	out := new(RulesDismissalRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesFileExtensionRestriction) DeepCopyInto(out *RulesFileExtensionRestriction) {
	*out = *in
	if in.RestrictedFileExtensions != nil {
		in, out := &in.RestrictedFileExtensions, &out.RestrictedFileExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesFileExtensionRestriction.
func (in *RulesFileExtensionRestriction) DeepCopy() *RulesFileExtensionRestriction {
	if in == nil {
		return nil
	}
	out := new(RulesFileExtensionRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesFilePathRestriction) DeepCopyInto(out *RulesFilePathRestriction) {
	*out = *in
	if in.RestrictedFilePaths != nil {
		in, out := &in.RestrictedFilePaths, &out.RestrictedFilePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoredFilePaths != nil {
		in, out := &in.IgnoredFilePaths, &out.IgnoredFilePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesFilePathRestriction.
func (in *RulesFilePathRestriction) DeepCopy() *RulesFilePathRestriction {
	if in == nil {
		return nil
	}
	out := new(RulesFilePathRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesMaxFilePathLength) DeepCopyInto(out *RulesMaxFilePathLength) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesMaxFilePathLength.
func (in *RulesMaxFilePathLength) DeepCopy() *RulesMaxFilePathLength {
	if in == nil {
		return nil
	}
	out := new(RulesMaxFilePathLength)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesMaxFileSize) DeepCopyInto(out *RulesMaxFileSize) {
	*out = *in
	if in.IgnoredFilePaths != nil {
		in, out := &in.IgnoredFilePaths, &out.IgnoredFilePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesMaxFileSize.
func (in *RulesMaxFileSize) DeepCopy() *RulesMaxFileSize {
	if in == nil {
		return nil
	}
	out := new(RulesMaxFileSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesMergeQueue) DeepCopyInto(out *RulesMergeQueue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesMergeQueue.
func (in *RulesMergeQueue) DeepCopy() *RulesMergeQueue {
	if in == nil {
		return nil
	}
	out := new(RulesMergeQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesPattern) DeepCopyInto(out *RulesPattern) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesPattern.
func (in *RulesPattern) DeepCopy() *RulesPattern {
	if in == nil {
		return nil
	}
	out := new(RulesPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesPullRequest) DeepCopyInto(out *RulesPullRequest) {
	*out = *in
	if in.AllowedMergeMethods != nil {
		in, out := &in.AllowedMergeMethods, &out.AllowedMergeMethods
		*out = make([]RulesMergeMethod, len(*in))
		copy(*out, *in)
	}
	if in.DismissalRestriction != nil {
		in, out := &in.DismissalRestriction, &out.DismissalRestriction
		*out = new(RulesDismissalRestriction)
		(*in).DeepCopyInto(*out)
	}
	if in.DismissStaleReviewsOnPush != nil {
		in, out := &in.DismissStaleReviewsOnPush, &out.DismissStaleReviewsOnPush
		*out = new(bool)
		**out = **in
	}
	if in.RequireExtraApprovalForUnattributedChanges != nil {
		in, out := &in.RequireExtraApprovalForUnattributedChanges, &out.RequireExtraApprovalForUnattributedChanges
		*out = new(bool)
		**out = **in
	}
	if in.RequiredReviewers != nil {
		in, out := &in.RequiredReviewers, &out.RequiredReviewers
		*out = make([]*RulesRequiredReviewer, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RulesRequiredReviewer)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RequireCodeOwnerReview != nil {
		in, out := &in.RequireCodeOwnerReview, &out.RequireCodeOwnerReview
		*out = new(bool)
		**out = **in
	}
	if in.RequireLastPushApproval != nil {
		in, out := &in.RequireLastPushApproval, &out.RequireLastPushApproval
		*out = new(bool)
		**out = **in
	}
	if in.RequiredApprovingReviewCount != nil {
		in, out := &in.RequiredApprovingReviewCount, &out.RequiredApprovingReviewCount
		*out = new(int)
		**out = **in
	}
	if in.RequiredReviewThreadResolution != nil {
		in, out := &in.RequiredReviewThreadResolution, &out.RequiredReviewThreadResolution
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesPullRequest.
func (in *RulesPullRequest) DeepCopy() *RulesPullRequest {
	if in == nil {
		return nil
	}
	out := new(RulesPullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesRequiredDeployments) DeepCopyInto(out *RulesRequiredDeployments) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesRequiredDeployments.
func (in *RulesRequiredDeployments) DeepCopy() *RulesRequiredDeployments {
	if in == nil {
		return nil
	}
	out := new(RulesRequiredDeployments)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesRequiredReviewer) DeepCopyInto(out *RulesRequiredReviewer) {
	*out = *in
	if in.FilePatterns != nil {
		in, out := &in.FilePatterns, &out.FilePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Reviewer = in.Reviewer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesRequiredReviewer.
func (in *RulesRequiredReviewer) DeepCopy() *RulesRequiredReviewer {
	if in == nil {
		return nil
	}
	out := new(RulesRequiredReviewer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesRequiredStatusChecks) DeepCopyInto(out *RulesRequiredStatusChecks) {
	*out = *in
	if in.DoNotEnforceOnCreate != nil {
		in, out := &in.DoNotEnforceOnCreate, &out.DoNotEnforceOnCreate
		*out = new(bool)
		**out = **in
	}
	if in.RequiredStatusChecks != nil {
		in, out := &in.RequiredStatusChecks, &out.RequiredStatusChecks
		*out = make([]*RulesRequiredStatusChecksParameters, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RulesRequiredStatusChecksParameters)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StrictRequiredStatusChecksPolicy != nil {
		in, out := &in.StrictRequiredStatusChecksPolicy, &out.StrictRequiredStatusChecksPolicy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesRequiredStatusChecks.
func (in *RulesRequiredStatusChecks) DeepCopy() *RulesRequiredStatusChecks {
	if in == nil {
		return nil
	}
	out := new(RulesRequiredStatusChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesRequiredStatusChecksParameters) DeepCopyInto(out *RulesRequiredStatusChecksParameters) {
	*out = *in
	if in.IntegrationId != nil {
		in, out := &in.IntegrationId, &out.IntegrationId
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesRequiredStatusChecksParameters.
func (in *RulesRequiredStatusChecksParameters) DeepCopy() *RulesRequiredStatusChecksParameters {
	if in == nil {
		return nil
	}
	out := new(RulesRequiredStatusChecksParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesReviewer) DeepCopyInto(out *RulesReviewer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesReviewer.
func (in *RulesReviewer) DeepCopy() *RulesReviewer {
	if in == nil {
		return nil
	}
	out := new(RulesReviewer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesSecretScanningAlertResolution) DeepCopyInto(out *RulesSecretScanningAlertResolution) {
	*out = *in
	if in.SecretTypes != nil {
		in, out := &in.SecretTypes, &out.SecretTypes
		*out = make([]RulesSecretType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesSecretScanningAlertResolution.
func (in *RulesSecretScanningAlertResolution) DeepCopy() *RulesSecretScanningAlertResolution {
	if in == nil {
		return nil
	}
	out := new(RulesSecretScanningAlertResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetByPassActors) DeepCopyInto(out *RulesetByPassActors) {
	*out = *in
	if in.ActorId != nil {
		in, out := &in.ActorId, &out.ActorId
		*out = new(int64)
		**out = **in
	}
	if in.ActorType != nil {
		in, out := &in.ActorType, &out.ActorType
		*out = new(string)
		**out = **in
	}
	if in.BypassMode != nil {
		in, out := &in.BypassMode, &out.BypassMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetByPassActors.
func (in *RulesetByPassActors) DeepCopy() *RulesetByPassActors {
	if in == nil {
		return nil
	}
	out := new(RulesetByPassActors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetConditions) DeepCopyInto(out *RulesetConditions) {
	*out = *in
	if in.RefName != nil {
		in, out := &in.RefName, &out.RefName
		*out = new(RulesetRefName)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetConditions.
func (in *RulesetConditions) DeepCopy() *RulesetConditions {
	if in == nil {
		return nil
	}
	out := new(RulesetConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetRefName) DeepCopyInto(out *RulesetRefName) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetRefName.
func (in *RulesetRefName) DeepCopy() *RulesetRefName {
	if in == nil {
		return nil
	}
	out := new(RulesetRefName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroup) DeepCopyInto(out *RunnerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroup.
func (in *RunnerGroup) DeepCopy() *RunnerGroup {
	if in == nil {
		return nil
	}
	out := new(RunnerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupList) DeepCopyInto(out *RunnerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupList.
func (in *RunnerGroupList) DeepCopy() *RunnerGroupList {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupObservation) DeepCopyInto(out *RunnerGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupObservation.
func (in *RunnerGroupObservation) DeepCopy() *RunnerGroupObservation {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupParameters) DeepCopyInto(out *RunnerGroupParameters) {
	*out = *in
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedRepositories != nil {
		in, out := &in.SelectedRepositories, &out.SelectedRepositories
		*out = make([]RunnerGroupSelectedRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectedWorkflows != nil {
		in, out := &in.SelectedWorkflows, &out.SelectedWorkflows
		*out = make([]WorkflowRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupParameters.
func (in *RunnerGroupParameters) DeepCopy() *RunnerGroupParameters {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupSelectedRepo) DeepCopyInto(out *RunnerGroupSelectedRepo) {
	*out = *in
	if in.RepoRef != nil {
		in, out := &in.RepoRef, &out.RepoRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoSelector != nil {
		in, out := &in.RepoSelector, &out.RepoSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupSelectedRepo.
func (in *RunnerGroupSelectedRepo) DeepCopy() *RunnerGroupSelectedRepo {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupSelectedRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupSpec) DeepCopyInto(out *RunnerGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupSpec.
func (in *RunnerGroupSpec) DeepCopy() *RunnerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupStatus) DeepCopyInto(out *RunnerGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupStatus.
func (in *RunnerGroupStatus) DeepCopy() *RunnerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretConfiguration) DeepCopyInto(out *SecretConfiguration) {
	*out = *in
	if in.ActionsSecrets != nil {
		in, out := &in.ActionsSecrets, &out.ActionsSecrets
		*out = make([]OrgSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DependabotSecrets != nil {
		in, out := &in.DependabotSecrets, &out.DependabotSecrets
		*out = make([]OrgSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretConfiguration.
func (in *SecretConfiguration) DeepCopy() *SecretConfiguration {
	if in == nil {
		return nil
	}
	out := new(SecretConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelectedRepo) DeepCopyInto(out *SecretSelectedRepo) {
	*out = *in
	if in.RepoRef != nil {
		in, out := &in.RepoRef, &out.RepoRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoSelector != nil {
		in, out := &in.RepoSelector, &out.RepoSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelectedRepo.
func (in *SecretSelectedRepo) DeepCopy() *SecretSelectedRepo {
	if in == nil {
		return nil
	}
	out := new(SecretSelectedRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberTeam) DeepCopyInto(out *TeamMemberTeam) {
	*out = *in
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.TeamSelector != nil {
		in, out := &in.TeamSelector, &out.TeamSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberTeam.
func (in *TeamMemberTeam) DeepCopy() *TeamMemberTeam {
	if in == nil {
		return nil
	}
	out := new(TeamMemberTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberUser) DeepCopyInto(out *TeamMemberUser) {
	*out = *in
	if in.UserRef != nil {
		in, out := &in.UserRef, &out.UserRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserSelector != nil {
		in, out := &in.UserSelector, &out.UserSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberUser.
func (in *TeamMemberUser) DeepCopy() *TeamMemberUser {
	if in == nil {
		return nil
	}
	out := new(TeamMemberUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamObservation) DeepCopyInto(out *TeamObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamObservation.
func (in *TeamObservation) DeepCopy() *TeamObservation {
	if in == nil {
		return nil
	}
	out := new(TeamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamParameters) DeepCopyInto(out *TeamParameters) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TeamMemberUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OrgRef != nil {
		in, out := &in.OrgRef, &out.OrgRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgSelector != nil {
		in, out := &in.OrgSelector, &out.OrgSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(string)
		**out = **in
	}
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ParentSelector != nil {
		in, out := &in.ParentSelector, &out.ParentSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Privacy != nil {
		in, out := &in.Privacy, &out.Privacy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamParameters.
func (in *TeamParameters) DeepCopy() *TeamParameters {
	if in == nil {
		return nil
	}
	out := new(TeamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateRepo) DeepCopyInto(out *TemplateRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateRepo.
func (in *TemplateRepo) DeepCopy() *TemplateRepo {
	if in == nil {
		return nil
	}
	out := new(TemplateRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnappliedBranchProtection) DeepCopyInto(out *UnappliedBranchProtection) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnappliedBranchProtection.
func (in *UnappliedBranchProtection) DeepCopy() *UnappliedBranchProtection {
	if in == nil {
		return nil
	}
	out := new(UnappliedBranchProtection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnappliedSetting) DeepCopyInto(out *UnappliedSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnappliedSetting.
func (in *UnappliedSetting) DeepCopy() *UnappliedSetting {
	if in == nil {
		return nil
	}
	out := new(UnappliedSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSelectedRepo) DeepCopyInto(out *VariableSelectedRepo) {
	*out = *in
	if in.RepoRef != nil {
		in, out := &in.RepoRef, &out.RepoRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoSelector != nil {
		in, out := &in.RepoSelector, &out.RepoSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSelectedRepo.
func (in *VariableSelectedRepo) DeepCopy() *VariableSelectedRepo {
	if in == nil {
		return nil
	}
	out := new(VariableSelectedRepo)
	in.DeepCopyInto(out)
	return out
}
