/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Membership.
func (mg *Membership) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.Org,
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = rsp.ResolvedValue
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Organization.
func (mg *Organization) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i4 := 0; i4 < len(mg.Spec.ForProvider.Actions.EnabledRepos); i4++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Actions.EnabledRepos[i4].Repo,
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Actions.EnabledRepos[i4].RepoRef,
			Selector:     mg.Spec.ForProvider.Actions.EnabledRepos[i4].RepoSelector,
			To: reference.To{
				List:    &RepositoryList{},
				Managed: &Repository{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Actions.EnabledRepos[i4].Repo")
		}
		mg.Spec.ForProvider.Actions.EnabledRepos[i4].Repo = rsp.ResolvedValue
		mg.Spec.ForProvider.Actions.EnabledRepos[i4].RepoRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Repository.
func (mg *Repository) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i4 := 0; i4 < len(mg.Spec.ForProvider.Permissions.Users); i4++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Permissions.Users[i4].User,
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Permissions.Users[i4].UserRef,
			Selector:     mg.Spec.ForProvider.Permissions.Users[i4].UserSelector,
			To: reference.To{
				List:    &MembershipList{},
				Managed: &Membership{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Permissions.Users[i4].User")
		}
		mg.Spec.ForProvider.Permissions.Users[i4].User = rsp.ResolvedValue
		mg.Spec.ForProvider.Permissions.Users[i4].UserRef = rsp.ResolvedReference

	}
	for i4 := 0; i4 < len(mg.Spec.ForProvider.Permissions.Teams); i4++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Permissions.Teams[i4].Team,
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Permissions.Teams[i4].TeamRef,
			Selector:     mg.Spec.ForProvider.Permissions.Teams[i4].TeamSelector,
			To: reference.To{
				List:    &TeamList{},
				Managed: &Team{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Permissions.Teams[i4].Team")
		}
		mg.Spec.ForProvider.Permissions.Teams[i4].Team = rsp.ResolvedValue
		mg.Spec.ForProvider.Permissions.Teams[i4].TeamRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.Org,
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = rsp.ResolvedValue
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Team.
func (mg *Team) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Members); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Members[i3].User,
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Members[i3].UserRef,
			Selector:     mg.Spec.ForProvider.Members[i3].UserSelector,
			To: reference.To{
				List:    &MembershipList{},
				Managed: &Membership{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Members[i3].User")
		}
		mg.Spec.ForProvider.Members[i3].User = rsp.ResolvedValue
		mg.Spec.ForProvider.Members[i3].UserRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.Org,
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = rsp.ResolvedValue
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parent),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ParentRef,
		Selector:     mg.Spec.ForProvider.ParentSelector,
		To: reference.To{
			List:    &TeamList{},
			Managed: &Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Parent")
	}
	mg.Spec.ForProvider.Parent = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentRef = rsp.ResolvedReference

	return nil
}
