---
# Variable available to all repositories in the organization.
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: OrganizationVariable
metadata:
  name: sample-variable-all
  annotations:
    crossplane.io/external-name: SAMPLE_VAR_ALL
spec:
  forProvider:
    orgRef:
      name: pgh-sample-organization
    value: hello-all
    visibility: all
---
# Variable available only to selected repositories.
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: OrganizationVariable
metadata:
  name: sample-variable-selected
  annotations:
    crossplane.io/external-name: SAMPLE_VAR_SELECTED
spec:
  forProvider:
    orgRef:
      name: pgh-sample-organization
    value: hello-some
    visibility: selected
    selectedRepositories:
    - repoRef:
        name: pgh-sample-repository
