---
apiVersion: v1
data:
  foo_com: LW5ldyBzb1NlY3JldE11Y2hXb3cxMzM3Cg==
kind: Secret
metadata:
  name: sample-repository-webhook-secrets
  namespace: production
type: Opaque
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: sample-repository
spec:
  writeConnectionSecretToRef:
    name: sample-repository-repo-state
    namespace: production
  forProvider:
    createFromTemplate:
      owner: octo-org
      repo: octo-template
      includeAllBranches: true
    description: This is a sample repository
    orgRef: 
      name: pgh-sample-organization
    permissions:
      users:
      - userRef: 
          name: pgh-sample-user
        role: push
      teams:
      - teamRef:
          name: sample-team
        role: pull
    webhooks:
    - active: true
      contentType: json
      events:
      - workflow_job
      insecureSsl: false
      url: https://example.com
    - active: true
      contentType: json
      events:
      - workflow_job
      insecureSsl: false
      url: https://foo.com
      secretKeyRef:
        key: foo_com
        name: sample-repository-webhook-secrets
        namespace: production
    branchProtectionRules:
      - branch: main
        enforceAdmins: true
        requireLinearHistory: true
        requiredConversationResolution: true
        requiredPullRequestReviews:
          dismissStaleReviews: true
          requiredApprovingReviewCount: 1
          requireCodeOwnerReviews: true
          requireLastPushApproval: true
          bypassPullRequestAllowances:
            users:
              - ci-user
        requiredStatusChecks:
          strict: true
          checks:
            - context: terraform_validate
            - context: deploy
              appId: 123456
    repositoryRules:
      - name: test-ruleset-2
        target: branch
        bypassActors:
          - actorId: 8743474
            actorType: Team
            bypassMode: always
          - actorId: 1
            actorType: OrganizationAdmin
            bypassMode: always
          - actorId: 397599
            actorType: Integration
            bypassMode: always
          - actorId: 2
            actorType: RepositoryRole
            bypassMode: always
        conditions:
          refName:
            include:
              [ ]
            exclude:
              - refs/heads/exclude
              - refs/heads/feature/exclude
        rules:
          creation: false
          nonFastForward: true
          requiredLinearHistory: true
          deletion: true
          update: true
          requiredSignatures: true
          requiredDeployments:
              environments:
                - production-github
          pullRequest:
            dismissStaleReviewsOnPush: false
            requiredApprovingReviewCount: 4
            requireCodeOwnerReview: true
            requireLastPushApproval: true
            requiredReviewThreadResolution: true
          requiredStatusChecks:
            strictRequiredStatusChecksPolicy: true
            requiredStatusChecks:
              - context: validate
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: sample-fork
spec:
  forProvider:
    description: This is a sample fork
    orgRef: 
      name: pgh-sample-organization
    createFork:
      owner: some-org
      repo: some-repo
      defaultBranchOnly: true
