---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: sample-repository
spec:
  forProvider:
    createFromTemplate:
      owner: octo-org
      repo: octo-template
      includeAllBranches: true
    description: This is a sample repository
    orgRef: 
      name: pgh-sample-organization
    permissions:
      users:
      - userRef: 
          name: pgh-sample-user
        role: push
      teams:
      - teamRef:
          name: sample-team
        role: pull
    webhooks:
    - active: true
      contentType: json
      events:
      - workflow_job
      insecureSsl: false
      url: https://example.com
    branchProtectionRules:
      - branch: main
        enforceAdmins: true
        requireLinearHistory: true
        requiredConversationResolution: true
        requiredPullRequestReviews:
          dismissStaleReviews: true
          requiredApprovingReviewCount: 1
          requireCodeOwnerReviews: true
          requireLastPushApproval: true
          bypassPullRequestAllowances:
            users:
              - ci-user
        requiredStatusChecks:
          strict: true
          checks:
            - context: terraform_validate
            - context: deploy
              appId: 123456
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: sample-fork
spec:
  forProvider:
    description: This is a sample fork
    orgRef: 
      name: pgh-sample-organization
    createFork:
      owner: some-org
      repo: some-repo
      defaultBranchOnly: true
