---
# Runner group available to all repositories in the organization.
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: RunnerGroup
metadata:
  name: sample-runner-group-all
  annotations:
    crossplane.io/external-name: shared-runners
spec:
  forProvider:
    orgRef:
      name: pgh-sample-organization
    visibility: all
---
# Runner group available only to selected repositories and restricted
# to specific workflows.
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: RunnerGroup
metadata:
  name: sample-runner-group-selected
  annotations:
    crossplane.io/external-name: deploy-runners
spec:
  forProvider:
    orgRef:
      name: pgh-sample-organization
    visibility: selected
    selectedRepositories:
    - repoRef:
        name: pgh-sample-repository
    selectedWorkflows:
    - example-org/example-repo/.github/workflows/deploy.yml@refs/heads/main
