name: OSV-Scanner PR

on:
  pull_request: {}

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # Fails only on vulnerabilities the PR introduces relative to its base branch.
  scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc # v2.6.0
    with:
      upload-sarif: false
